development: &default
  adapter: postgresql
  database: bca_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

production:
  <<: *default
  database: bca_test

test:
  <<: *default
  database: bca_test
